/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'brpu2352' at '3/3/15 4:17 PM' with Gradle 2.2.1
 *
 * @author brpu2352, @date 3/3/15 4:17 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
