/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'brpu2352' at '3/3/15 4:17 PM' with Gradle 2.2.1
 *
 * @author brpu2352, @date 3/3/15 4:17 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
